name: OneTime Build

on: [workflow_dispatch] # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 编译 Linux AMD64 纯二进制文件
      - name: Build Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o prom2parquet main.go

      # 2. 编译并打包 Linux AMD64 Docker 镜像
      - name: Build Docker Image Tar
        run: |
          docker build -t prom2parquet:latest .
          docker save prom2parquet:latest | gzip > prom2parquet_image.tar.gz

      # 3. 把【二进制】和【镜像包】一并上传到网页供你下载
      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: prom2parquet-outputs
          path: |
            prom2parquet
            prom2parquet_image.tar.gz
