---
name: OneTime Build For Codasda

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Binary
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o prom2parquet main.go

      - name: Build Docker Image Tar
        run: |
          docker build -t prom2parquet:latest .
          docker save prom2parquet:latest | gzip > prom2parquet_image.tar.gz

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: prom2parquet-outputs
          path: |
            prom2parquet
            prom2parquet_image.tar.gz
